### PR TITLE
Modification of the ASR ROS API to 2.1

### PR DESCRIPTION
**Pull request by jordiadell**
I need to add this changes to pal_interaction_msgs, sadly this will break the api, and we need to synchronize with a commit in robot. So, please inform me asap when you apply the changes.

### CODE REVIEW

**Comment by po1** [comment]
Welcome to github \o/

**Comment by bmagyar** [comment]
should we change the author of the commits to some github user?

**Comment by po1** [comment]
@jordiadell do you know if there is any dependency to this on stacks/wet packages? I can help you figure this out. Also, please have a patch ready to commit for robot when we merge this PR.

**Comment by po1** [comment]
> should we change the author of the commits to some github user?

We should at least give them a proper name. _System User_ is not very pretty. I'll help @jordiadell configure his git client.

**Comment by jordiadell** [comment]
For what concerns user names, I you need to tell me what to do. Because I put my username and passwd when pushing the commits. But, github does not use this apparently.
I did not change any stack/wet dependencies, just msg definitions. So this should not be a problem.

**Comment by po1** [comment]
Well you removed the `ASRGrammarMngmt` message. If anything is using it in our stacks, it will break. Also, why did you not remove the file itself?

**Comment by jordiadell** [comment]
Only ASR in Robot is using them. And may be some very recent robocup
robotcup code.
I removed that file itself, because the new one is a generalization of the old one.

**Comment by po1** [comment]
Much better now :+1: 
merging

**Pull request merged**
