### PR TITLE
Fix minor typos and 0 codes

### PR DESCRIPTION
**Pull request by awesomebytes**
Fixing using 0 on some enums and some minor typos.

### CODE REVIEW

**Comment by bmagyar** [comment]
why 0 codes?

**Comment by po1** [comment]
`0` is the default value of `int8` fields in a ROS message.
This means that uninitialized values will be reported as a valid enum state, which is most often undesirable.

Also, coding regular states as positive integers and negative states as negative is a common practice, somewhere. By some people.

+0 here.
I like the change, but I won't raise my thumb before I have proof that it doesn't break everything that uses these messages, including unit tests.

**Comment by awesomebytes** [comment]
I still need to test it, I did this pull request so jordi could evaluate
the changes. Also I'll do a couple changes more. Give me some time please.

**Comment by po1** [comment]
No problem, no rush for this.

**Comment by awesomebytes** [comment]
Tested with basestation, robot and tools. Fixed some changes that were needed in robot. Already commited, so merging here.

**Pull request merged**
