### PR TITLE
added srv for changing actuator current limit

### PR DESCRIPTION
**Pull request by lucamarchionni**
Simple service requests for dynamically change the current limit of an actuator.

### CODE REVIEW

**Comment by po1** [comment]
looks fine (despite being a service)

:+1:

**Comment by lucamarchionni** [comment]
could we merge this pull request?

**Comment by adolfo-rt** [comment]
Hey, late joiner to the party. Was on holidays yesterday.

We should coordinate interfaces and how they are used by controllers. You had no way of knowing about this until now, but there exists a branch of this repo that defines a message type for setting the maximum current for a group of actuators, and supports the degenerate case of one:
https://github.com/pal-robotics/pal_msgs/blob/max-curr/pal_control_msgs/msg/ActuatorCurrentLimit.msg

At the very least we should harmonize between `max_current` (what I'm using) and `current_limit` (what you're using) names, not only for the message but for the `ros_control` interfaces and controller names, so that there is uniformity.

My original intention was to have a topic-based mechanism for setting max currents, as it allows for 'fast' periodic updates as well as for single-shot updates. I'm not a big fan of services, but we could consider having a controller that exposes both a topic and a service API.

What is evident is that we need to sit down and discuss our usecases.

@awesomebytes

**Comment by adolfo-rt** [comment]
For the record, I like `current_limit` more than `max_current`, and have updated the message name and spec accordingly.

**Pull request merged**
